{
    'name': 'Farm Management Project',
    'summary': 'Farm Management Project',
    'description': """ Farm Management Project """,
    'sequence': -1,
    'version': '15.0.0',
    'author': 'Mordant Business Solutions',
    'website': 'https://www.mordantbs.com',
    'category': 'Farm/Farm',
    'license': 'OPL-1',
    'depends': ['mail', 'contacts', 'base_setup', 'sale', 'sale_management', 'hr', 'hr_expense', 'product'],
    'data': [
        'views/crop.xml',
        'views/employee_views.xml',
        'views/equipment_views.xml',
        'views/vehical.xml',
        'views/farm_task_for_worker.xml',
        'data/sequence_order.xml',
        'data/sequence_eqp.xml',
        'data/cron_file.xml',
        'data/email_template.xml',
        'security/ir.model.access.csv',
        'report/report_menu.xml',
        'report/worker_task_report.xml',
        'report/agri_qweb_report.xml',
        # 'report/layout.xml',
    ],
    'images':['static/description/farm_banner2.jpg',
              'static/description/farm_banner3.png',
              'static/description/farm_banner1.jpg'],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
